sudo: required
language: generic


services:
    - docker
    
before_install:
    - docker build -t jrbe2288/react-test -f ./client/Dockerfile.dev ./client 
    
script:
    - docker run -e CI=true jrbe2288/react-test npm test
    
after_success:
    - docker build -t jrbe228/multi-client ./client
    - docker build -t jrbe228/multi-nginx ./nginx
    - docker build -t jrbe228/multi-server ./server
    - docker build -t jrbe228/multi-worker ./worker
    # Log in to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take images and push to Dockerhub
    - docker push jrbe228/multi-client
    - docker push jrbe228/multi-nginx
    - docker push jrbe228/multi-server
    - docker push jrbe228/multi-worker