sudo: required
language: generic


services:
    - docker
    
before_install:
    - docker build -t jrbe228/react-test -f ./client/Dockerfile.dev ./client 
    
script:
    - docker run -e CI=true jrbe228/react-test npm test
    
after_success:
    - docker build -t jrbe228/multi-client ./client
    - docker build -t jrbe228/multi-nginx ./nginx
    - docker build -t jrbe228/multi-server ./server
    - docker build -t jrbe228/multi-worker ./worker
    # Log in to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take images and push to Dockerhub
    - docker push jrbe228/multi-client
    - docker push jrbe228/multi-nginx
    - docker push jrbe228/multi-server
    - docker push jrbe228/multi-worker
    
deploy:
    provider: elasticbeanstalk
    region: 'us-east-2'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-us-east-2-012256633746'
    bucket_path: 'docker-multi'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY